//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarrerLib
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Jobs_Posted = new HashSet<Jobs_Posted>();
        }
    
        public int compId { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please  enter Company name"), MaxLength(30)]
        [Display(Name = "Company Name")]
        public string compNamae { get; set; }
       
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please  enter Company Branch name"), MaxLength(30)]
        [Display(Name = "Company Branch Name")]
        public string compBranch { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please  enter Company Address"), MaxLength(30)]
        [Display(Name = "Company  Address Name")]
        public string compAddress { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please  enter  City name"), MaxLength(30)]
        [Display(Name = "City Name")]
        public string compCity { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please  enter  State name"), MaxLength(30)]
        [Display(Name = "State Name")]
        public string compState { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please enter Email ID")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        [Display(Name = "E-mail")]
        public string compEmail { get; set; }
        [Required(ErrorMessage = "Please enter Mobile No")]
        [Display(Name = "Contact Number")]
        [DataType(DataType.PhoneNumber)]
        public long compPhone { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please Enter password")]
        [Display(Name = "Password")]
        public string compPassword { get; set; }
        [Display(Name = "User Name")]

        public string compUsername { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobs_Posted> Jobs_Posted { get; set; }
    }
}
