//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarrerLib
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Job_Seeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job_Seeker()
        {
            this.JobSeeker_Professional = new HashSet<JobSeeker_Professional>();
        }
    
        public int jsID { get; set; }
        
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please  enter name"), MaxLength(30)]
        [Display(Name = "Full Name")]
       
        public string jsFullName { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please enter Email ID")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        [Display(Name = "E-mail")]

        public string jsEmail { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please Enter password") ]
        [Display(Name = "Password")]

        public string jsPassword { get; set; }

        [Required(ErrorMessage = "Please enter Mobile No")]
        [Display(Name = "Contact Number")]
        [DataType(DataType.PhoneNumber)]
        public long jsPhone { get; set; }

        [Required(ErrorMessage = "Please enter your date of bithday")]
        [Display(Name = "D.O.B")]
        [DataType(DataType.Date)]
        public System.DateTime jsDOB { get; set; }
        [Display(Name = "City")]
        [DataType(DataType.Text)]
        public string jsCity { get; set; }
        [Display(Name = "State")]
        [DataType(DataType.Text)]
        public string jsState { get; set; }
        [Display(Name = "Martial Status")]
        public string jsMartialStatus { get; set; }
        [Display(Name = "language Peferred")]
        public string jsLanguagePreferred { get; set; }
        [Display(Name = "Resume")]
        public string jsResume { get; set; }
        [Display(Name = "Major")]
        [DataType(DataType.Text)]
        public string jsMajor { get; set; }
        [Display(Name = "University")]
        [DataType(DataType.Text)]
        public string jsUniversity { get; set; }
        [Display(Name = "Institute")]
        [DataType(DataType.Text)]
        public string jsInstitute { get; set; }
        [Display(Name = "Year of Graduation")]
        public int jsYearOfGraduation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeeker_Professional> JobSeeker_Professional { get; set; }
    }
}
