//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarrerLib
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class JobSeeker_Professional
    {
        public int jsProfID { get; set; }
        [Display(Name = "Your enrollment Id")]
        public int jsID { get; set; }
        [Display(Name = " Key skill")]
        public string jsKeySkills { get; set; }
        [Display(Name = "Preferred Industry")]
        public string jsPreferredIndustry { get; set; }
        [Display(Name = "Year of Experience")]
        public Nullable<int> jsYearOfExperience { get; set; }
        [Display(Name = "Previous Company  Name")]
        public string jsPrevcompName { get; set; }
        [Display(Name = "Previous Title")]
        public string jsPreviousTitile { get; set; }
        [Display(Name = "Previous Job Description")]
        public string JsPrevJobDescription { get; set; }
    
        public virtual Job_Seeker Job_Seeker { get; set; }
    }
}
