//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarrerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsApplied
    {
        public int AppliedJobsID { get; set; }
        public string jsName { get; set; }
        public int JobID { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public Nullable<int> cmpid { get; set; }
    }
}
